// ==UserScript==
// @name         [Frg] Google to DuckDuckGo redirect
// @namespace	 https://github.com/Frigvid/scripts-and-userstyles
// @author       Frigvid
// @description  Redirects from Google while keeping your query.
// @version      1.33.67
// @icon         https://raw.githubusercontent.com/Frigvid/scripts-and-userstyles/master/resources/favicons/duckduckgo.png
// @updateURL    https://github.com/Frigvid/scripts-and-userstyles/raw/master/scripts/redirects/google_to_duckduckgo.user.js
// @downloadURL  https://github.com/Frigvid/scripts-and-userstyles/raw/master/scripts/redirects/google_to_duckduckgo.user.js
// @supportURL   https://github.com/Frigvid/scripts-and-userstyles/issues
// @noframes
// @include      https://www.google.com/*
// @include      https://www.google.ad/*
// @include      https://www.google.ae/*
// @include      https://www.google.com.af/*
// @include      https://www.google.com.ag/*
// @include      https://www.google.com.ai/*
// @include      https://www.google.al/*
// @include      https://www.google.am/*
// @include      https://www.google.co.ao/*
// @include      https://www.google.com.ar/*
// @include      https://www.google.as/*
// @include      https://www.google.at/*
// @include      https://www.google.com.au/*
// @include      https://www.google.az/*
// @include      https://www.google.ba/*
// @include      https://www.google.com.bd/*
// @include      https://www.google.be/*
// @include      https://www.google.bf/*
// @include      https://www.google.bg/*
// @include      https://www.google.com.bh/*
// @include      https://www.google.bi/*
// @include      https://www.google.bj/*
// @include      https://www.google.com.bn/*
// @include      https://www.google.com.bo/*
// @include      https://www.google.com.br/*
// @include      https://www.google.bs/*
// @include      https://www.google.bt/*
// @include      https://www.google.co.bw/*
// @include      https://www.google.by/*
// @include      https://www.google.com.bz/*
// @include      https://www.google.ca/*
// @include      https://www.google.cd/*
// @include      https://www.google.cf/*
// @include      https://www.google.cg/*
// @include      https://www.google.ch/*
// @include      https://www.google.ci/*
// @include      https://www.google.co.ck/*
// @include      https://www.google.cl/*
// @include      https://www.google.cm/*
// @include      https://www.google.cn/*
// @include      https://www.google.com.co/*
// @include      https://www.google.co.cr/*
// @include      https://www.google.com.cu/*
// @include      https://www.google.cv/*
// @include      https://www.google.com.cy/*
// @include      https://www.google.cz/*
// @include      https://www.google.de/*
// @include      https://www.google.dj/*
// @include      https://www.google.dk/*
// @include      https://www.google.dm/*
// @include      https://www.google.com.do/*
// @include      https://www.google.dz/*
// @include      https://www.google.com.ec/*
// @include      https://www.google.ee/*
// @include      https://www.google.com.eg/*
// @include      https://www.google.es/*
// @include      https://www.google.com.et/*
// @include      https://www.google.fi/*
// @include      https://www.google.com.fj/*
// @include      https://www.google.fm/*
// @include      https://www.google.fr/*
// @include      https://www.google.ga/*
// @include      https://www.google.ge/*
// @include      https://www.google.gg/*
// @include      https://www.google.com.gh/*
// @include      https://www.google.com.gi/*
// @include      https://www.google.gl/*
// @include      https://www.google.gm/*
// @include      https://www.google.gr/*
// @include      https://www.google.com.gt/*
// @include      https://www.google.gy/*
// @include      https://www.google.com.hk/*
// @include      https://www.google.hn/*
// @include      https://www.google.hr/*
// @include      https://www.google.ht/*
// @include      https://www.google.hu/*
// @include      https://www.google.co.id/*
// @include      https://www.google.ie/*
// @include      https://www.google.co.il/*
// @include      https://www.google.im/*
// @include      https://www.google.co.in/*
// @include      https://www.google.iq/*
// @include      https://www.google.is/*
// @include      https://www.google.it/*
// @include      https://www.google.je/*
// @include      https://www.google.com.jm/*
// @include      https://www.google.jo/*
// @include      https://www.google.co.jp/*
// @include      https://www.google.co.ke/*
// @include      https://www.google.com.kh/*
// @include      https://www.google.ki/*
// @include      https://www.google.kg/*
// @include      https://www.google.co.kr/*
// @include      https://www.google.com.kw/*
// @include      https://www.google.kz/*
// @include      https://www.google.la/*
// @include      https://www.google.com.lb/*
// @include      https://www.google.li/*
// @include      https://www.google.lk/*
// @include      https://www.google.co.ls/*
// @include      https://www.google.lt/*
// @include      https://www.google.lu/*
// @include      https://www.google.lv/*
// @include      https://www.google.com.ly/*
// @include      https://www.google.co.ma/*
// @include      https://www.google.md/*
// @include      https://www.google.me/*
// @include      https://www.google.mg/*
// @include      https://www.google.mk/*
// @include      https://www.google.ml/*
// @include      https://www.google.com.mm/*
// @include      https://www.google.mn/*
// @include      https://www.google.ms/*
// @include      https://www.google.com.mt/*
// @include      https://www.google.mu/*
// @include      https://www.google.mv/*
// @include      https://www.google.mw/*
// @include      https://www.google.com.mx/*
// @include      https://www.google.com.my/*
// @include      https://www.google.co.mz/*
// @include      https://www.google.com.na/*
// @include      https://www.google.com.ng/*
// @include      https://www.google.com.ni/*
// @include      https://www.google.ne/*
// @include      https://www.google.nl/*
// @include      https://www.google.no/*
// @include      https://www.google.com.np/*
// @include      https://www.google.nr/*
// @include      https://www.google.nu/*
// @include      https://www.google.co.nz/*
// @include      https://www.google.com.om/*
// @include      https://www.google.com.pa/*
// @include      https://www.google.com.pe/*
// @include      https://www.google.com.pg/*
// @include      https://www.google.com.ph/*
// @include      https://www.google.com.pk/*
// @include      https://www.google.pl/*
// @include      https://www.google.pn/*
// @include      https://www.google.com.pr/*
// @include      https://www.google.ps/*
// @include      https://www.google.pt/*
// @include      https://www.google.com.py/*
// @include      https://www.google.com.qa/*
// @include      https://www.google.ro/*
// @include      https://www.google.ru/*
// @include      https://www.google.rw/*
// @include      https://www.google.com.sa/*
// @include      https://www.google.com.sb/*
// @include      https://www.google.sc/*
// @include      https://www.google.se/*
// @include      https://www.google.com.sg/*
// @include      https://www.google.sh/*
// @include      https://www.google.si/*
// @include      https://www.google.sk/*
// @include      https://www.google.com.sl/*
// @include      https://www.google.sn/*
// @include      https://www.google.so/*
// @include      https://www.google.sm/*
// @include      https://www.google.sr/*
// @include      https://www.google.st/*
// @include      https://www.google.com.sv/*
// @include      https://www.google.td/*
// @include      https://www.google.tg/*
// @include      https://www.google.co.th/*
// @include      https://www.google.com.tj/*
// @include      https://www.google.tl/*
// @include      https://www.google.tm/*
// @include      https://www.google.tn/*
// @include      https://www.google.to/*
// @include      https://www.google.com.tr/*
// @include      https://www.google.tt/*
// @include      https://www.google.com.tw/*
// @include      https://www.google.co.tz/*
// @include      https://www.google.com.ua/*
// @include      https://www.google.co.ug/*
// @include      https://www.google.co.uk/*
// @include      https://www.google.com.uy/*
// @include      https://www.google.co.uz/*
// @include      https://www.google.com.vc/*
// @include      https://www.google.co.ve/*
// @include      https://www.google.vg/*
// @include      https://www.google.co.vi/*
// @include      https://www.google.com.vn/*
// @include      https://www.google.vu/*
// @include      https://www.google.ws/*
// @include      https://www.google.rs/*
// @include      https://www.google.co.za/*
// @include      https://www.google.co.zm/*
// @include      https://www.google.co.zw/*
// @include      https://www.google.cat/*
// ==/UserScript==

var regExpr = /&q(?:\\)?=([^&]+)/g;
var regEx = new RegExp(regExpr);
var linkLoc = location.href;

if (linkLoc.match(regEx)) {
  console.log(linkLoc.match(regEx));
} else {
  console.log("No match");
}

queryReplace = '?';
queryReplacee = (linkLoc.match(regEx))+""; //Bloody retarded fucking arrays
queryResult = queryReplace + queryReplacee.slice(1);
console.log(queryResult);

location.replace('https://duckduckgo.com' + queryResult);
